spring:
  datasource:
    druid:
      url: jdbc:mysql://116.62.148.139:3306/cloud_user?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8&useSSL=false
      username:
      password:
  redis:
    host: 116.62.148.139
    port: 6379
    password:
    database: 2

